New Admin Panel/noochAdminNew/noochAdminNew/Models/Member.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.MemberNotifications = new HashSet<MemberNotification>();
            this.PasswordResetRequests = new HashSet<PasswordResetRequest>();
            this.SynapseBankLoginResults = new HashSet<SynapseBankLoginResult>();
            this.Transactions = new HashSet<Transaction>();
            this.Transactions1 = new HashSet<Transaction>();
        }
    
        public System.Guid MemberId { get; set; }
        public string Nooch_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UDID1 { get; set; }
        public string UserName { get; set; }
        public string SecondaryEmail { get; set; }
        public string RecoveryEmail { get; set; }
        public string TertiaryEmail { get; set; }
        public string PinNumber { get; set; }
        public string Password { get; set; }
        public string ContactNumber { get; set; }
        public string Status { get; set; }
        public Nullable<bool> RememberMeEnabled { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> InvalidLoginTime { get; set; }
        public Nullable<int> InvalidLoginAttemptCount { get; set; }
        public Nullable<int> InvalidPinAttemptCount { get; set; }
        public Nullable<System.DateTime> InvalidPinAttemptTime { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string FacebookAccountLogin { get; set; }
        public Nullable<bool> AllowPushNotifications { get; set; }
        public string Photo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public Nullable<bool> ShowInSearch { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Deposit { get; set; }
        public Nullable<System.DateTime> InviteReminderDate { get; set; }
        public string UserNameLowerCase { get; set; }
        public string TimeZoneKey { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> TotalNoochTransfersCount { get; set; }
        public Nullable<int> TotalACHTransfersCount { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public Nullable<int> ValidationFailedCount { get; set; }
        public Nullable<System.Guid> InviteCodeId { get; set; }
        public Nullable<System.Guid> InviteCodeIdUsed { get; set; }
        public string Type { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> UpgradeDate { get; set; }
        public Nullable<bool> IsVerifiedPhone { get; set; }
        public Nullable<decimal> LastLocationLat { get; set; }
        public Nullable<decimal> LastLocationLng { get; set; }
        public string AccessToken { get; set; }
        public Nullable<bool> Allow2FactorAuthentication { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<System.DateTime> SDNCheckDateTime { get; set; }
        public Nullable<bool> AnyPriliminaryHit { get; set; }
        public Nullable<long> ent_num { get; set; }
        public Nullable<bool> IsRequiredImmediatley { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<bool> IsSDNSafe { get; set; }
        public string AdminNotes { get; set; }
        public Nullable<System.DateTime> PhoneVerifiedOn { get; set; }
        public string VerificationDocumentPath { get; set; }
        public Nullable<bool> IsVerifiedWithSynapse { get; set; }
        public string TransferLimit { get; set; }
        public string FacebookUserId { get; set; }
        public string GoogleUserId { get; set; }
    
        public virtual ICollection<MemberNotification> MemberNotifications { get; set; }
        public virtual ICollection<PasswordResetRequest> PasswordResetRequests { get; set; }
        public virtual ICollection<SynapseBankLoginResult> SynapseBankLoginResults { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Transaction> Transactions1 { get; set; }
    }
}

New Admin Panel/noochAdminNew/noochAdminNew/Controllers/MemberController.cs
using noochAdminNew.Classes.ModelClasses;
using noochAdminNew.Classes.ResponseClasses;
using noochAdminNew.Classes.Utility;
using noochAdminNew.Models;
using System;
using System.Collections.Generic;
using System.Data.Objects.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using noochAdminNew.Resources;

namespace noochAdminNew.Controllers
{
    public class MemberController : Controller
    {
        [HttpPost]
        [ActionName("ApplyOperation")]
        public ActionResult ApplyOperation(string operation, string noochIds)
        {
            MemberOperationsResult mr = new MemberOperationsResult();

            if (operation == "0")
            {
                mr.IsSuccess = false;
                mr.Message = "No operation selected to perform";
                return Json(mr);
            }

            if (noochIds.Length == 0)
            {
                mr.IsSuccess = false;
                mr.Message = "No user selected to perfrom action";
                return Json(mr);
            }


            try
            {
                noochIds = noochIds.TrimEnd(',');
                List<string> allNoochIdsChoosen = noochIds.Split(',').ToList<string>();

                List<MemberOperationsInnerClass> allinnerclass = new List<MemberOperationsInnerClass>();

                #region Suspend

                if (operation == "1")
                {
                    // Suspend User

                    foreach (string s in allNoochIdsChoosen)
                    {
                        using (NOOCHEntities obj = new NOOCHEntities())
                        {
                            var member = (from t in obj.Members where t.Nooch_ID == s && t.Status != Constants.STATUS_SUSPENDED select t).SingleOrDefault();
                            MemberOperationsInnerClass mic = new MemberOperationsInnerClass();

                            #region IfMemberNotNull
                            if (member != null)
                            {
                                member.Status = Constants.STATUS_SUSPENDED;
                                member.InvalidLoginAttemptCount = 3;
                                member.InvalidPinAttemptCount = null;
                                member.InvalidLoginTime = DateTime.Now;
                                member.InvalidPinAttemptTime = null;
                                member.DateModified = DateTime.Now;
                                member.ModifiedBy = Utility.ConvertToGuid(Session["UserId"].ToString());
                                obj.SaveChanges();

                                // sending email to member
                                var fromAddress = Utility.GetValueFromConfig("adminMail");
                                string emailAddress = CommonHelper.GetDecryptedData(member.UserName);

                                var tokens = new Dictionary<string, string>
                                {
                                    {Constants.PLACEHOLDER_FIRST_NAME,CommonHelper.UppercaseFirst(CommonHelper.GetDecryptedData(member.FirstName))}
                                };

                                try
                                {
                                    Utility.SendEmail("userSuspended", fromAddress, emailAddress,
                                        "Your Nooch account has been suspended", null, tokens, null, null, null);

                                    Logger.Info("Admin Dash -> MemberController - SupendMember email sent to: [" + emailAddress + "]; Member [memberId:" +
                                                member.MemberId + "]");

                                    mic.Message = "Member Suspended Successfully";
                                    mic.NoochId = member.Nooch_ID;
                                    mic.IsSuccess = true;
                                    allinnerclass.Add(mic);
                                }
                                catch (Exception)
                                {
                                    // to return the status without inserting records in notifications or friends tables, when mail is not sent successfully.
                                    Logger.Error("Admin Dash -> MemberController - SupendMember email NOT send to: [" + emailAddress + "]; Member [memberId:" +
                                                member.MemberId + "]. Problem occured in sending mail.");

                                    mic.Message = "Member Suspension Failed";
                                    mic.NoochId = member.Nooch_ID;
                                    mic.IsSuccess = false;
                                    allinnerclass.Add(mic);
                                }
                            }
                            else
                            {
                                mic.Message = "Member already Suspended";
                                mic.NoochId = s;
                                allinnerclass.Add(mic);
                            }
                            #endregion

                        }
                    }
                    mr.IsSuccess = true;
                    mr.Message = "all operations performed";
                    mr.MemberOperationsOuterClass = allinnerclass;
                }

                #endregion Suspend


                #region SDN Safe

                if (operation == "2")
                {
                    // Mark User as SDN Safe

                    foreach (string s in allNoochIdsChoosen)
                    {
                        using (NOOCHEntities obj = new NOOCHEntities())
                        {
                            var member = (from t in obj.Members where t.Nooch_ID == s && t.IsSDNSafe == null || t.IsSDNSafe == false select t).SingleOrDefault();
                            MemberOperationsInnerClass mic = new MemberOperationsInnerClass();

                            #region IfMemberNotNull

                            if (member != null)
                            {
                                try
                                {
                                    member.IsSDNSafe = true;
                                    member.DateModified = DateTime.Now;
                                    member.ModifiedBy = Utility.ConvertToGuid(Session["UserId"].ToString());
                                    obj.SaveChanges();

                                    Logger.Error("Admin Dash -> Members Controller - Mark SDN Safe - MemberId: [" +
                                                member.MemberId + "]");

                                    mic.Message = "Member marked SDN safe Successfully. ";
                                    mic.NoochId = member.Nooch_ID;
                                    mic.IsSuccess = true;
                                    allinnerclass.Add(mic);
                                }
                                catch (Exception)
                                {
                                    // to return the status without inserting records in notifications or friends tables, when mail is not sent successfully.
                                    Logger.Error("Admin Dash -> Members Controller - Mark SDN Safe FAILED - MemberId: [" +
                                                member.MemberId + "]");

                                    mic.Message = "Member SDN mark safe failed!";
                                    mic.NoochId = member.Nooch_ID;
                                    mic.IsSuccess = false;
                                    allinnerclass.Add(mic);
                                }
                            }
                            else
                            {
                                mic.Message = "Member already SDN Safe ";
                                mic.NoochId = s;
                                allinnerclass.Add(mic);
                            }
                            #endregion

                        }
                    }
                    mr.IsSuccess = true;
                    mr.Message = "all operations performed";
                    mr.MemberOperationsOuterClass = allinnerclass;
                }

                #endregion SDN Safe


                #region verify phone

                if (operation == "3")
                {
                    // Verify User's Phone Number

                    foreach (string s in allNoochIdsChoosen)
                    {
                        using (NOOCHEntities obj = new NOOCHEntities())
                        {
                            var member = (from t in obj.Members where t.Nooch_ID == s && t.ContactNumber != null select t).SingleOrDefault();
                            MemberOperationsInnerClass mic = new MemberOperationsInnerClass();
                            #region IfMemberNotNull
                            if (member != null)
                            {
                                try
                                {
                                    member.IsVerifiedPhone = true;
                                    member.DateModified = DateTime.Now;
                                    member.PhoneVerifiedOn = DateTime.Now;
                                    member.ModifiedBy = Utility.ConvertToGuid(Session["UserId"].ToString());
                                    obj.SaveChanges();

                                    Logger.Error("VerifyPhone - Attempt to verify member phone[ memberId:" +
                                                member.MemberId + "].");

                                    mic.Message = "Contact no. verified Successfully. ";
                                    mic.NoochId = member.Nooch_ID;
                                    mic.IsSuccess = true;
                                    allinnerclass.Add(mic);

                                }

New Admin Panel/noochAdminNew/noochAdminNew/Views/Member/GrowthGraphs.cshtml
@{
    ViewBag.Title = "GrowthGraphs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="wrapper wrapper-content">


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>Growth Charts</h2>
        </div>
    </div>
    <div class="row">
    </div>
</div>


<script>
    $(document).ready(function () {
        $("#MemberMenuExpander").trigger("click");
        $("#growthcharts").addClass('active');
    });
</script>

New Admin Panel/noochAdminNew/noochAdminNew/Views/Member/ListAll.cshtml
@using noochAdminNew.Classes.ModelClasses;
@{
    ViewBag.Title = "ListAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Data Tables CSS -->
<link href="~/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="~/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="~/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Nooch Members</h2>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">

        <div class="col-lg-12" id="memListAllTableDiv">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>All Nooch Members</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        @* <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">Config option 1</a>
                                </li>
                                <li><a href="#">Config option 2</a>
                                </li>
                            </ul>*@
                    </div>
                </div>

                <div class="ibox-content">

                    <div class="row">
                        <div class="col-xs-9 col-sm-3 m-b-xs">
                            <select class="input-sm form-control input-s-sm inline" id="opMaster">
                                <option value="0"> -- Select Action -- </option>
                                <option value="1"> Suspend Users </option>
                                <option value="2"> Mark SDN Safe </option>
                                <option value="3"> Verify Phone </option>
                                <option value="4"> Activate Users </option>
                                <option value="5"> Delete Users </option>
                            </select>
                        </div>
                        @* <div class="col-sm-4 m-b-xs">
                              <div class="btn-group" data-toggle="buttons">
                                          <label class="btn btn-sm btn-white active"> <input type="radio" name="options" id="option1"> Day </label>
                                          <label class="btn btn-sm btn-white"> <input type="radio" name="options" id="option2"> Week </label>
                                          <label class="btn btn-sm btn-white"> <input type="radio" name="options" id="option3"> Month </label>
                                      </div>
                            </div>*@
                        <div class="col-xs-3" id="memListAll_ApplyChg">
                            <div class="input-group">
                                @*<input type="text" class="input-sm form-control" placeholder="Search"> *@
                                <span class="input-group-btn">
                                    <button class="btn btn-sm btn-primary" type="button" onclick="Member.ApplyChoosenOperation();">Apply Changes</button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <table class="table table-striped table-bordered table-hover" id="AllMembers">
                        <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="selecctall" name="chkMaster">
                                </th>
                                <th>Nooch ID</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Username</th>
                                <th>Contact #</th>
                                <th>Joined On</th>
                                <th>Status</th>
                                <th>City</th>
                                <th>Total Transactions</th>
                                <th>Total $ Sent</th>
                            </tr>
                        </thead>

                        <tbody id="TBOdy">

                            @foreach (MembersListDataClass M in Model)
                            {
                                <tr class="gradeX">
                                    <td><input type="checkbox" class="checkbox1" name="chk" value="@M.Nooch_ID" onclick="chkboxClick(this)"></td>
                                    <td><a href="@Url.Action("Detail", "Member", new { NoochId=@M.Nooch_ID} )">@M.Nooch_ID</a></td>
                                    <td>@M.FirstName</td>
                                    <td>@M.LastName</td>
                                    <td>@M.UserName</td>
                                    <td>@M.ContactNumber<br />
                                    @{
                                if (M.IsVerifiedPhone == true)
                                {
                                    <span class="small text-success">Verified</span>
                                }
                                else if (M.ContactNumber != null)
                                {
                                    <span class="small text-danger">Not Verified</span>
                                }
                                    }
                                </td>
                                <td>@M.DateCreated.ToString("dd MMM yyyy")</td>
                                <td>@M.Status</td>
                                <td>@M.City</td>
                                <td>@M.TotalTransactions</td>
                                <td>@M.TotalAmountSent</td>
                            </tr>
                            }

                        </tbody>
                        <tfoot>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Users Over Time</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">Config option 1</a>
                            </li>
                            <li>
                                <a href="#">Config option 2</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="ibox-content">
                    <div id="rickshaw_bars" class="rickshaw_graph"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Stacked Bars</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">Config option 1</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="ibox-content">
                    <div id="rickshaw_bars_stacked" class="rickshaw_graph"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Chart Title</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">Config option 1</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="ibox-content">
                    <div id="rickshaw_bars_stacked" class="rickshaw_graph"></div>
                </div>
            </div>
        </div>
    </div>

</div>


<!-- Data Tables JS-->
<script src="~/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="~/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script src="~/js/plugins/dataTables/dataTables.responsive.js"></script>
<script src="~/js/plugins/dataTables/dataTables.tableTools.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="~/Scripts/App/Utility.js"></script>
<script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script src="~/Scripts/App/MembersList.js"></script>


<script type="text/ecmascript">
    $(document).ready(function () {
        $("#MemberMenuExpander").trigger("click");

        $('#ListAllMembersMenu').addClass('active');

        $('#AllMembers').dataTable({
            responsive: true,
            "order": [[6,'desc'], [7,'asc'], [3,'asc'], [2,'asc']],
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "../js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
            },
            "columnDefs": [
                   { "orderable": false, "targets": [ 0,5 ] }
            ]
        });
    });
</script>


<script>
    window.paceOptions = {
        ajax: {
            trackMethods: ['GET', 'POST', 'PUT', 'DELETE', 'REMOVE']
        }
    };
</script>

<style>
    body.DTTT_Print {
        background: #fff;
    }

    .DTTT_Print #page-wrapper {
        margin: 0;
        background: #fff;
    }

    button.DTTT_button, div.DTTT_button, a.DTTT_button {
        border: 1px solid #e7eaec;
        background: #fff;
        color: #676a6c;
        box-shadow: none;
        padding: 6px 8px;
    }

        button.DTTT_button:hover, div.DTTT_button:hover, a.DTTT_button:hover {
            border: 1px solid #d2d2d2;
            background: #fff;
            color: #676a6c;
            box-shadow: none;
            padding: 6px 8px;
        }

    .dataTables_filter label {
        margin-right: 5px;
    }
</style>